export const MESSAGE_PATTERNS = {
  auth: {
    register: { cmd: 'auth.register' },
    login: { cmd: 'auth.login' },
    logout: { cmd: 'auth.logout' },
    forgotPassword: { cmd: 'auth.forgot_password' },
    resetPassword: { cmd: 'auth.reset_password' },
    profile: { cmd: 'auth.profile' },
    updatePassword: { cmd: 'auth.update_password' },
    updateProfile: { cmd: 'auth.update_profile' },
    findAllUsers: { cmd: 'auth.find_all_users' },
    findUserById: { cmd: 'auth.find_user_by_id' },
    updateUserRole: { cmd: 'auth.update_user_role' },
    deleteUser: { cmd: 'auth.delete_user' },
    validateToken: { cmd: 'auth.validate_token' },
  },
  products: {
    create: { cmd: 'products.create' },
    findAll: { cmd: 'products.find_all' },
    findAdmin: { cmd: 'products.find_admin' },
    findOne: { cmd: 'products.find_one' },
    update: { cmd: 'products.update' },
    delete: { cmd: 'products.delete' },
    createReview: { cmd: 'products.create_review' },
    findReviews: { cmd: 'products.find_reviews' },
    deleteReview: { cmd: 'products.delete_review' },
    decreaseStock: { cmd: 'products.decrease_stock' },
  },
  orders: {
    created: 'ORDER_CREATED',
    create: { cmd: 'orders.create' },
    findMine: { cmd: 'orders.find_mine' },
    findAll: { cmd: 'orders.find_all' },
    findOne: { cmd: 'orders.find_one' },
    updateStatus: { cmd: 'orders.update_status' },
    delete: { cmd: 'orders.delete' },
    cancelled: 'ORDER_CANCELLED'
  },
} as const;
